#!/usr/bin/with-contenv sh

umask 002

if [ $(grep target_app /etc/hosts | wc -l) -gt "0" ]
    then
        FORWARD_HOST="target_app"
    else
        FORWARD_HOST=$(ip route | grep default | awk "{print \$3}")
fi

s6-echo "Forwarding $LISTEN_PORT -> $FORWARD_HOST:$FORWARD_PORT"

exec socat tcp-listen:${LISTEN_PORT},fork tcp-connect:${FORWARD_HOST}:${FORWARD_PORT}
