#!/usr/bin/with-contenv sh

umask 002

echo "Forwarding $LISTEN_PORT -> $FORWARD_PORT" 2> /var/log/socat

exec socat tcp-listen:${LISTEN_PORT},fork tcp-connect:$(ip route | grep default | awk "{print \$3}"):${FORWARD_PORT}
