#!/usr/bin/with-contenv sh

umask 002

ECHO "Forwarding $LISTEN_PORT -> $FORWARD_PORT"

exec socat tcp-listen:${LISTEN_PORT},fork tcp-connect:$(ip route | grep default | awk "{print \$3}"):${FORWARD_PORT}
